{
    "data":{
    "1":"Don't listen to the babble\nPut your hand in, you'll get stuck",
    "2":"Sour bamboo shoots cooked with fish at the source\nLife changes, when sad when happy.",
    "3": "Love each other tearing silk to sew pants\nHate each other telling each other debts",
    "4":"Whoever, don't laugh at each other\nThere is no tree without worms touching the branches",
    "5": "No one can help you when you're rich\nWhen you're in trouble, no one can help you",
    "6":"Stay in a way that pleases people\nExpand people laugh, stay narrow, people criticize.",
    "7":"The wise bird has not been caught yet,\nThe wise man rarely speaks, seldom answers",
    "8": "Bitter medicine, disheartening truth.",
    "9": "One lie, seven days of repentance.",
    "10": "Sweet words to the bone",
    "11": "Delicious food is remembered for a long time, painful words are forever remembered",
    "12":"The blade is sharper than the sword",
    "13":"Boneless tongue, many twisty lines.",
    "14": "It's better to stumble than to lose your mouth.",
    "15": "Good news goes far, bad news goes far.",
    "16": "One person is closed, two people are open.",
    "17": "Easy to say, hard to do.",
    "18":"Flexible young bamboo",
    "19": "Baby does not vin, even broken branches.",
    "20": "Love for the leap, hate for the play",
    "21": "If you teach me, I will be smart, if my father teaches me, I will be smart.",
    "22":"Learning to eat, learn to speak, learn to open learning packages",
    "23": "No matter how ignorant you are, you will know it after studying for a long time.",
    "24": "A clumsy person weaving a basket in the middle of the road.",
    "25": "No, I dare you to do it.",
    "26": "Study from a teacher can't learn from a friend.",
    "27": "There is a new record to translate so tuong.",
    "28": "Good writing doesn't worry about long lines.",
    "29": "Literature, your wife.",
    "30": "Being gentle, meeting good.",
    "31": "In the star meet the ghost, in the ghost meet the monster, the wicked meet.",
    "32": "A man's venom is equal to ten snake venoms.",
    "33": "One life harms and corrupts three generations.",
    "34":"The Lobster kills the sleeping lobster,\nThe killer stays awake for five hours.",
    "35": "Wife wife, don't see your wife.",
    "36":"Too gentle turns stupid.",
    "37":"Kill a stork, save a hundred shrimps.",
    "38": "Pretty is better than pretty.",
    "39": "The habit of killing beauty.",
    "40": "Hungry to clean, tear to smell.",
    "41": "It is better to die in than to live in turbidity.",
    "42": "Good or bad, stupid or wordy.",
    "43": "Who likes melons, old gourds.",
    "44":"The good shows, the evil hides.",
    "45":"Silver head is not yet wild.",
    "46":"Wise for three years, foolish for an hour.",
    "47":"Wise people talk half way\nLet fools be happy and worried at the same time.",
    "48": "Wise to make literary sacrifices, foolish to make epitaphs.",
    "49": "Eat the meal first, wade later.",
    "50":"There is no such thing as a rabid.",
    "51": "The fool enjoys peace",
    "52": "Fools hurt the wise.",
    "53":"Wildly for people to fear,\nWild for people to love,\nBad for people to hate.",
    "54":"Clumsy rowing well.",
    "55": "Clumsy dancing and deviating land.",
    "56": "Praise the good, criticize the cowardly.",
    "57":"Ten francs in wages,\n Not as much as a bonus coin.",
    "58": "A buffalo dies for its skin, a dead man for a voice.",
    "59":"Better fame than good clothes.",
    "60": "More lovers than haters.",
    "61": "Love the young, the young come home; love the old, get old for happiness.",
    "62": "If you love each other nine, you will make ten\nIf you are present, you will scold, if you are absent, you will be loved.",
    "63": "Love each other, bite each other hurts.",
    "64": "Love should be good, hate should be bad.",
    "65":"Love someone, love you all the way,\nHate each other, hate all relatives.",
    "66":"Hate each other to dig up the dirt",
    "67":"Sometimes people are glorious and sometimes shameful,\nWater is sometimes cloudy and sometimes clear.",
    "68": "Very happy, suffering a lot.",
    "69":"Love people as if you love yourself",
    "70": "Good leaves cover torn leaves\n pale to know how to love cats.",
    "71": "If you give up, you will be hurt, if you are king, you will be guilty.",
    "72": "When you eat fruit, remember who planted the tree.",
    "73":"Drink water, remember the source.",
    "74":"One night stay, one year stay.",
    "75":"The trail, grace does not wear out.",
    "76": "Not sour lemons, sweet, don't be greedy.",
    "77":"Hoi rice raising wild storks",
    "78": "Breaked by birds, forgotten by fish.",
    "79":"Eat bowl of porridge.",
    "80": "I can't help but forget the teacher.",
    "81": "There are bones and rivers, love and affection.",
    "82":"There is moon, auxiliary lights.",
    "83": "One sentence of fasting is nine good sentences.",
    "84": "Avoiding elephants is not ugly.",
    "85": "The cock crowed.",
    "86": "Fighting to divide rice, greeting each other for rice.",
    "87":"Even anger is lost.",
    "88": "A little bit angry with strangers.",
    "89": "One life sues, nine generations of enemies.",
    "90": "Eat it right away, tell the truth, all vices are good.",
    "91":"Triple tree is not afraid of standing still",
    "92": "Has a startling habit, has a period in the stomach.",
    "93":"Straight ink train heartbreaking wood.",
    "94": "Lost first, gain later.",
    "95":"Sweet honey kills flies,\nbitter places are honest.",
    "96":"The field buffalo eats the field grass.",
    "97": "Eat any tree that fences that tree.",
    "98": "The buffalo body is taken care of, the cow's body is raw.",
    "99": "No one cries in common.",
    "100": "The neighbor's house is on fire, it's like a jar.",
    "101":"Nostalgic to buy firecrackers, borrow people to burn.",
    "102": "Housework is lazy, uncle's work is diligent.",
    "103": "If you have a loan to pay, you will be satisfied.",
    "104":"Seafish a litter.",
    "105":"Turn off the lights on tiled houses as well as cottages.",
    "106": "As a mandarin, eat the king's fortune, in the temple eat the Buddha's fortune.",
    "107":"There are no thorns in the middle of the day,\nuntil there are fish to borrow a fish from someone.",
    "108":"The lazy person is not lazy.",
    "109": "Mouth and mouth support limbs.",
    "110": "Holding rice is sick, pounding nuggets is healthy.",
    "111": "If you're good at eating, you'll be full, if you're smart, you'll be warm.",
    "112":"Measure cows to make stables.",
    "113":"Weak legs run first.",
    "114": "Do it when it heals, save it when it hurts",
    "115":"Lost cows to build a barn.",
    "116": "If you have it, keep it.",
    "117": "Trading in ships and selling land is not as good as eating sparingly.",
    "118": "Dispose of flute shit to get banyan seeds, treat chicken shit to get broken seeds.",
    "119":"Finding firewood for three years and burning one hour",
    "120": "Father's life is round, son's life is squashed",
    "121":"The river avalanches sand",
    "122": "Fall in my heart, pity on people's hearts",
    "123":"Cheap fortune telling is better than sitting idle",
    "124":"You can't get a carp or a carp, but you can get a bunch of shrimps",
    "125":"Release the iron hunter, catch the perch",
    "126":"Fall in the sieve",
    "127": "Falling leaves return to the roots",
    "128": "Rice is not eaten, rice is still there",
    "129": "Rice spilled, singing is not full",
    "130":"Lost both lead and fishing rod",
    "131": "Get one human meal, lose ten family meals.",
    "132":"It was difficult, the dog bit more",
    "133": "Know where to avoid sin, know where to find happiness.",
    "134": "Drowsy met the mat again\nice eaters met the man standing on the street.",
    "135": "If you go at night, you will meet ghosts one day",
    "136":"Four nine has not passed, year three has come",
    "137":"Avoid melon shells, meet coconut shells",
    "138":"Running in the sky can't escape the sun",
    "139":"Medication can't cure life",
    "140": "When it's right, the sky will also favor people",
    "141":"Five fingers with long fingers, short fingers",
    "142":"Who bends the hook to fit the fish's mouth",
    "143":"Saints are sometimes mistaken",
    "144":"Pull out bugs",
    "145": "If you hit a snake, you must hit its head",
    "146": "Teaching the time to practice for trot.",
    "147": "If you have lice, you should.",
    "148": "High intentions are not equal to thick will",
    "149":"An ant that takes a long time is also full of nests",
    "150": "Having a merit to grind iron, having a day to make a needle",
    "151":"The ability to pick up equipment",
    "152": "A hundred torches can catch a frog",
    "153":"The water is still slapping",
    "154": "Win without pride, defeat without discouragement",
    "155":"The waves do not fall off the oars",
    "156":"The king lost to the daredevil",
    "157":"The mother gives birth to her young\nAnd the rooster and the hen have broilers",
    "158":"Heaven doesn't close anyone's door",
    "159": "Who is rich three generations, who is difficult three generations",
    "160": "Whose hand the flag goes to, he waved",
    "161":"Pen sa, dead chicken",
    "162":"If you grind rice, stop holding me",
    "163": "A lot of monks don't close the temple door",
    "164":"The belly makes the skin bear",
    "165":"Having the guts to steal, having the guts to take the blow",
    "166":"The dog is thin and tiger-faced",
    "167":"Shooting should not be, must pay for bullets",
    "168":"Hundred mulberries pour silkworm heads",
    "169":"Bad head is cooler",
    "170":"The little cat catches the baby mouse",
    "171":"Wide for double, narrow for single",
    "172":"Snails can't carry their own snails, but they still carry stakes for moss",
    "173":"Who dares to swing with elf",
    "174":"Sxdog with fat on the tail",
    "175":"I learned to crawl while learning to run",
    "176":"Haven't fought the shit and asked to fly",
    "177": "A frog sitting at the bottom of a well, looking at the sky with a swing",
    "178": "The dog is near the house, the chicken is near the coop",
    "179":"The donkey's body likes heavy",
    "180": "The strong use strength, the weak use imitation",
    "181": "There is porridge to ask for tea",
    "182":"Standing on this mountain and looking at that mountain",
    "183":"Deaf or speechless, speechless"
    "184": "Beggars for sticky rice gac",
    "185":"The old man still plays the drums",
    "186": "I cried, I just suckled",
    "187":"Who knows where to scratch it",
    "188":"A full frog is difficult to lure",
    "189": "Criticize what is given by heaven",
    "190":"If you hate shrimp, you have to eat shrimp,\criticize wilted water spinach, hug an old melon again.",
    "191": "If you eat eggs, don't eat children.",
    "192":"It's easy to brag",
    "193":"Early sacrifice from flies",
    "194":"Which afternoon wind covers that afternoon",
    "195":"The grasshoppers come in when they see the red fire.",
    "196":"Follow the fire",
    "197":"Thanks to the wind breaking bamboo shoots",
    "198":"Fat water chisel",
    "199":"Hedge toppled Ivy",
    "200": "The market has not yet met, the thief has come",
    "201":"Thick tangerine peel with pointed nails",
    "202":"The thief meets the old woman",
    "203":"Tenderness and let go",
    "204":"Healing is a dipper, broken is a lip",
    "205":"The earth is thrown away, the lead is thrown back",
    "206":"The high tray knocks over the full bowl",
    "207": "In the land of the blind, one-eyed man is king",
    "208": "Near the temple call me by my brother",
    "209":"Burning the house to the face of the mouse",
    "210":"The javelin must follow the javelin",
    "211":"Trot has to wear a backpack",
    "212":"Wrong one inch by one mile",
    "213": "Greed is deep, wrong is true",
    "214":"Death in river, dead in stream,\nno one drowned by lamp",
    "215":"There is water with fish",
    "216":"Where's the dove",
    "217":"In the middle without losing the leg",
    "218":"The rice is still falling in the mouth",
    "219":"One lost ten doubts",
    "220": "Toads have toad livers, ants have ant guts.",
    "221":"Buffalo's blood is like cow's blood",
    "222": "A figurative heart is like a figment of a heart",
    "223":"Three often go into one battle",
    "224":"Decrease my belly into a human belly",
    "225":"Foretelling ghosts, sweeping the house out of trash",
    "226":"Where's Jiangshan, that's heroic",
    "227": "There's no food for dogs, rice for chickens",
    "228":"Too blind to rain.",
    "229":"Overcooked",
    "230":"It hurts to climb high",
    "231":"Falling a lot",
    "232":"The old anchor broke the rope",
    "233":"Choose the face to send gold",
    "234": "Walking with the Buddha wearing a kashāya\n going with a ghost wearing a paper shirt",
    "235":"It's hard to get through with a big head",
    "236":"The bulb is round, the tube is long",
    "237":"Every vegetable has depth",
    "238":"Near the fire, burning my face",
    "239":"Fire becomes a plague",
    "240": "Near rich people eat nuggets with toothache\slow thieves take a beating",
    "241":"The flood flooded the whole village",
    "242": "Being full of teachers and pagodas",
    "243":"Bulls and cows butts each other, flies and mosquitoes die",
    "244":"Unplug the jungle",
    "245":"Cold open lips and teeth",
    "246":"Hitting the dog to look at the owner",
    "247":"Love your child for your child's sake",
    "248": "Away from the river, you have to take a boat",
    "249":"Open your mouth and catch your mouth",
    "250":"If you want to be round, you must have a mold,\n if you want to be square, you must have a ruler",
    "251":"Head to tail",
    "252":"Thousands of beginnings are difficult",
    "253":"The old one is the new one",
    "254":"First strange, then familiar",
    "255":"Gambling with familiar hands\n sleeping on a daily basis",
    "256":"Fantastic snack",
    "257":"Horse used to old ways",
    "258":"How do people, what dreams do",
    "259":"Better ignorant or liquid",
    "260":"Title small to big",
    "261":"Gathering the wind into a storm, bringing together the trees into the forest",
    "262": "Three people beat one, not one mouse is also lame",
    "263":"Thirty pots are full of pots",
    "264":"Equally bad than good",
    "265":"No way go green"
    "266":"There is a new powder that makes the paste",
    "267":"Holding the straw with a heavy belly",
    "268":"Playing with a sharp knife has a broken hand"
	}
}
